obstacle_range: 4.5
raytrace_range: 5.0
robot_radius: 0.5
inflation_radius: 0.4
max_obstacle_height: 0.6
min_obstacle_height: 0.0
obstacle_layer:
  enabled: true #使能障碍层
  observation_sources: scan
  scan: {data_type: LaserScan, topic: /rslidar, marking: true, clearing: true, expected_update_rate: 0}
