# Move base node parameters. For full documentation of the parameters in this file, please see
#
#  http://www.ros.org/wiki/move_base
#
shutdown_costmaps: false

controller_frequency: 5.0
controller_patience: 2.0


planner_frequency: 2.0
planner_patience: 2.0

oscillation_timeout: 10.0
oscillation_distance: 0.2

# local planner - default is trajectory rollout
base_local_planner: "dwa_local_planner/DWAPlannerROS"
 #alternatives: dwa_local_planner/DWAPlannerROS,teb_local_planner/TebLocalPlannerROS

base_global_planner: "global_planner/GlobalPlanner"
 #alternatives: global_planner/GlobalPlanner, carrot_planner/CarrotPlanner,navfn/NavfnROS


